export const FORM_PROYECT = 'FORM_PROYECT';
export const GET_PROYECTS = 'GET_PROYECTS';
export const ADD_PROYECT = 'ADD_PROYECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const ACTUAL_PROYECT = 'ACTUAL_PROYECT';
export const DELETE_PROYECT = 'DELETE_PROYECT';

export const PROYECT_TASKS = 'PROYECT_TASKS';
export const ADD_TASK = 'ADD_TASK';